//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobro
    {
        public int idCobro { get; set; }
        public Nullable<int> idMesa { get; set; }
        public decimal TotalCobro { get; set; }
        public string TipoPago { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Mesa Mesa { get; set; }
    }
}
