//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int idGasto { get; set; }
        public string Descripcion { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
